"""add cost_per_unit to stock

Revision ID: a672a4af697a
Revises: 8c31bdb4ea6f
Create Date: 2026-02-09 17:19:20.395084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a672a4af697a'
down_revision = '8c31bdb4ea6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('upi_merchant_name', sa.String(), nullable=True),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('restaurant_address', sa.String(), nullable=True),
    sa.Column('restaurant_phone', sa.String(), nullable=True),
    sa.Column('restaurant_email', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_restaurant_address'), 'restaurant', ['restaurant_address'], unique=False)
    op.create_index(op.f('ix_restaurant_restaurant_email'), 'restaurant', ['restaurant_email'], unique=False)
    op.create_index(op.f('ix_restaurant_restaurant_phone'), 'restaurant', ['restaurant_phone'], unique=False)
    op.create_index(op.f('ix_restaurant_upi_id'), 'restaurant', ['upi_id'], unique=False)
    op.create_index(op.f('ix_restaurant_upi_merchant_name'), 'restaurant', ['upi_merchant_name'], unique=False)
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'invoice', ['id'])
    op.create_unique_constraint(None, 'menu', ['id'])
    op.create_unique_constraint(None, 'menu_item', ['id'])
    op.create_unique_constraint(None, 'order', ['id'])
    op.create_unique_constraint(None, 'order_status', ['id'])
    op.create_unique_constraint(None, 'payment', ['id'])
    op.create_unique_constraint(None, 'qr_code', ['id'])
    op.create_unique_constraint(None, 'stock', ['id'])
    op.create_unique_constraint(None, 'table', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'table', type_='unique')
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_constraint(None, 'qr_code', type_='unique')
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_constraint(None, 'order_status', type_='unique')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'menu_item', type_='unique')
    op.drop_constraint(None, 'menu', type_='unique')
    op.drop_constraint(None, 'invoice', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_index(op.f('ix_restaurant_upi_merchant_name'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_upi_id'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_restaurant_phone'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_restaurant_email'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_restaurant_address'), table_name='restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
