"""add cost_per_unit to stock

Revision ID: 8c31bdb4ea6f
Revises: 
Create Date: 2026-02-09 15:32:54.155181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c31bdb4ea6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_category_category_id'), 'category', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_category_name'), 'category', ['category_name'], unique=False)
    op.create_table('menu',
    sa.Column('menu_id', sa.String(), nullable=True),
    sa.Column('item_list', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_menu_category_id'), 'menu', ['category_id'], unique=False)
    op.create_index(op.f('ix_menu_category_name'), 'menu', ['category_name'], unique=False)
    op.create_index(op.f('ix_menu_item_list'), 'menu', ['item_list'], unique=False)
    op.create_index(op.f('ix_menu_menu_id'), 'menu', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_price'), 'menu', ['price'], unique=False)
    op.create_index(op.f('ix_menu_quantity'), 'menu', ['quantity'], unique=False)
    op.create_table('order',
    sa.Column('item_list', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_pending', sa.String(), nullable=True),
    sa.Column('order_done', sa.String(), nullable=True),
    sa.Column('order_cancel', sa.String(), nullable=True),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_order_item_list'), 'order', ['item_list'], unique=False)
    op.create_index(op.f('ix_order_quantity'), 'order', ['quantity'], unique=False)
    op.create_index(op.f('ix_order_table_no'), 'order', ['table_no'], unique=False)
    op.create_table('stock',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_stock_cost_per_unit'), 'stock', ['cost_per_unit'], unique=False)
    op.create_index(op.f('ix_stock_name'), 'stock', ['name'], unique=False)
    op.create_index(op.f('ix_stock_quantity'), 'stock', ['quantity'], unique=False)
    op.create_index(op.f('ix_stock_unit_of_measure'), 'stock', ['unit_of_measure'], unique=False)
    op.create_table('table',
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_table_table_no'), 'table', ['table_no'], unique=False)
    op.create_table('user',
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number_country_code', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_number_verified', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_table('invoice',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    op.create_table('menu_item',
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_price', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_item_name'), 'menu_item', ['item_name'], unique=False)
    op.create_index(op.f('ix_menu_item_item_price'), 'menu_item', ['item_price'], unique=False)
    op.create_table('order_status',
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_order_status_status'), 'order_status', ['status'], unique=False)
    op.create_table('payment',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('upi_ref_id', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('qr_code',
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('qr_data', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_code')
    op.drop_table('payment')
    op.drop_index(op.f('ix_order_status_status'), table_name='order_status')
    op.drop_table('order_status')
    op.drop_index(op.f('ix_menu_item_item_price'), table_name='menu_item')
    op.drop_index(op.f('ix_menu_item_item_name'), table_name='menu_item')
    op.drop_table('menu_item')
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_table_table_no'), table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_stock_unit_of_measure'), table_name='stock')
    op.drop_index(op.f('ix_stock_quantity'), table_name='stock')
    op.drop_index(op.f('ix_stock_name'), table_name='stock')
    op.drop_index(op.f('ix_stock_cost_per_unit'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_order_table_no'), table_name='order')
    op.drop_index(op.f('ix_order_quantity'), table_name='order')
    op.drop_index(op.f('ix_order_item_list'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_menu_quantity'), table_name='menu')
    op.drop_index(op.f('ix_menu_price'), table_name='menu')
    op.drop_index(op.f('ix_menu_menu_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_item_list'), table_name='menu')
    op.drop_index(op.f('ix_menu_category_name'), table_name='menu')
    op.drop_index(op.f('ix_menu_category_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_category_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
